"""baseline income, expenses, household context

Revision ID: 262afc3549c4
Revises: ce24d8406b27
Create Date: 2026-09-07 08:20:26.381477
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.base  # noqa: F401


revision: str = '262afc3549c4'
down_revision: str | None = 'ce24d8406b27'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Adding a NOT NULL column to a table that already has rows needs a value
# for those rows. Autogenerate does not know the Python-side default, so
# each addition below carries an explicit server_default.
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseline_incomes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('basis', sa.String(length=16), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('created_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("basis IN ('GROSS','NET','UNKNOWN')", name='ck_baseline_basis'),
    sa.CheckConstraint('amount_minor >= 0', name='ck_baseline_amount_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baseline_incomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baseline_incomes_user_id'), ['user_id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('income_stream_id', sa.String(length=32), nullable=True),
    sa.Column('application_id', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('incurred_on', sa.Date(), nullable=False),
    sa.Column('has_receipt', sa.String(length=16), nullable=False),
    sa.Column('partly_private', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_minor >= 0', name='ck_expense_amount_non_negative'),
    sa.CheckConstraint('income_stream_id IS NULL OR application_id IS NULL', name='ck_expense_has_one_parent'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['income_stream_id'], ['income_streams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('ix_expense_user_date', ['user_id', 'incurred_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_incurred_on'), ['incurred_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_children', sa.String(length=24), nullable=False,
                      server_default='UNKNOWN'))
        batch_op.add_column(sa.Column('jointly_assessed', sa.String(length=24), nullable=False,
                      server_default='UNKNOWN'))
        batch_op.add_column(sa.Column('children', app.db.base.JsonDict(), nullable=False,
                      server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('children')
        batch_op.drop_column('jointly_assessed')
        batch_op.drop_column('has_children')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_user_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_incurred_on'))
        batch_op.drop_index(batch_op.f('ix_expenses_category'))
        batch_op.drop_index(batch_op.f('ix_expenses_application_id'))
        batch_op.drop_index('ix_expense_user_date')

    op.drop_table('expenses')
    with op.batch_alter_table('baseline_incomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baseline_incomes_user_id'))

    op.drop_table('baseline_incomes')
    # ### end Alembic commands ###
