"""initial schema

Revision ID: ce24d8406b27
Revises: 
Create Date: 2026-09-04 14:33:56.380458
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.base

revision: str = 'ce24d8406b27'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before knowledge_chunks.embedding is created, because
    # app.db.base.Vector renders as the real vector type on Postgres. On a
    # managed instance without superuser rights this CREATE may be refused; that
    # is survivable, so it is attempted and not required - the column then
    # renders as text and app.rag.store falls back to an exhaustive numpy scan.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        try:
            op.execute("CREATE EXTENSION IF NOT EXISTS vector")
        except Exception:  # noqa: BLE001 - lack of rights is not a failed migration
            pass

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('subject_hash', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', app.db.base.JsonDict(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_subject_hash'), ['subject_hash'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('topic', sa.String(length=40), nullable=False),
    sa.Column('effective_year', sa.Integer(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_available', sa.Boolean(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_content_available'), ['content_available'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_effective_year'), ['effective_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_topic'), ['topic'], unique=False)

    op.create_table('legal_facts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('structured_value', app.db.base.JsonDict(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('content_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legal_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_facts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_facts_effective_from'), ['effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_facts_jurisdiction'), ['jurisdiction'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_facts_last_verified_at'), ['last_verified_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_facts_verification_status'), ['verification_status'], unique=False)
        batch_op.create_index('ix_legal_lookup', ['jurisdiction', 'category', 'verification_status'], unique=False)

    op.create_table('opportunity_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('access_basis', sa.Text(), nullable=True),
    sa.Column('last_health_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_check_ok', sa.Boolean(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunity_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_sources_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_sources_source_type'), ['source_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('external_auth_id', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_external_auth_id'), ['external_auth_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_demo'), ['is_demo'], unique=False)

    op.create_table('analytics_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('properties', app.db.base.JsonDict(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_events_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_analytics_name_time', ['name', 'occurred_at'], unique=False)

    op.create_table('child_goals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('child_label', sa.String(length=80), nullable=False),
    sa.Column('child_age_years', sa.Integer(), nullable=False),
    sa.Column('target_age_years', sa.Integer(), nullable=False),
    sa.Column('target_minor', sa.Integer(), nullable=False),
    sa.Column('current_minor', sa.Integer(), nullable=False),
    sa.Column('monthly_contribution_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('target_age_years > child_age_years', name='ck_child_ages_ordered'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('child_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_child_goals_user_id'), ['user_id'], unique=False)

    op.create_table('consent_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_records_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_records_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_consent_user_purpose', ['user_id', 'purpose'], unique=False)

    op.create_table('cv_documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cv_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cv_documents_user_id'), ['user_id'], unique=False)

    op.create_table('financial_goals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('goal_type', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_minor', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('current_minor', sa.Integer(), nullable=False),
    sa.Column('monthly_contribution_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_goals_goal_type'), ['goal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_goals_user_id'), ['user_id'], unique=False)

    op.create_table('income_goals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('target_monthly_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_goals_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_goals_user_id'), ['user_id'], unique=False)

    op.create_table('income_streams',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('money_state', sa.String(length=16), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('basis', sa.String(length=20), nullable=False),
    sa.Column('tax_treatment', sa.String(length=10), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status <> 'ACTIVE' OR money_state IN ('SECURED', 'EARNED')", name='ck_active_stream_is_committed'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income_streams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_streams_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_streams_money_state'), ['money_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_streams_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_streams_user_id'), ['user_id'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('topic', sa.String(length=40), nullable=False),
    sa.Column('effective_year', sa.Integer(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', app.db.base.Vector(), nullable=True),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'ordinal', name='uq_chunk_position')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_chunk_topic_year', ['topic', 'effective_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_topic'), ['topic'], unique=False)

    op.create_table('llm_usage',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.String(length=48), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_micros', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_kind', sa.String(length=48), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_purpose'), ['purpose'], unique=False)
        batch_op.create_index('ix_llm_usage_purpose_time', ['purpose', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notification_unread', ['user_id', 'read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('opportunities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('organization', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('subcategory', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('remote_type', sa.String(length=16), nullable=False),
    sa.Column('required_skills', app.db.base.StringList(), nullable=False),
    sa.Column('preferred_skills', app.db.base.StringList(), nullable=False),
    sa.Column('required_languages', app.db.base.JsonDict(), nullable=False),
    sa.Column('experience_min_years', sa.Float(), nullable=True),
    sa.Column('experience_max_years', sa.Float(), nullable=True),
    sa.Column('eligibility_text', sa.Text(), nullable=True),
    sa.Column('eligibility_structured', app.db.base.JsonDict(), nullable=False),
    sa.Column('employment_type', sa.String(length=24), nullable=False),
    sa.Column('compensation_min_minor', sa.Integer(), nullable=True),
    sa.Column('compensation_max_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('compensation_basis', sa.String(length=20), nullable=False),
    sa.Column('compensation_period', sa.String(length=16), nullable=False),
    sa.Column('tax_treatment', sa.String(length=10), nullable=False),
    sa.Column('compensation_verified', sa.Boolean(), nullable=False),
    sa.Column('estimated_hours_min', sa.Float(), nullable=True),
    sa.Column('estimated_hours_max', sa.Float(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('source_name', sa.String(length=160), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('is_sponsored', sa.Boolean(), nullable=False),
    sa.Column('evidence_confidence', sa.String(length=20), nullable=False),
    sa.Column('safety_verdict', sa.String(length=16), nullable=False),
    sa.Column('safety_reasons', app.db.base.StringList(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('NOT (is_demo AND compensation_verified)', name='ck_demo_cannot_be_verified'),
    sa.CheckConstraint('compensation_min_minor IS NULL OR compensation_max_minor IS NULL OR compensation_min_minor <= compensation_max_minor', name='ck_compensation_range_ordered'),
    sa.ForeignKeyConstraint(['source_id'], ['opportunity_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_fingerprint'), ['fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_opportunities_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_organization'), ['organization'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_remote_type'), ['remote_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_safety_verdict'), ['safety_verdict'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_source_type'), ['source_type'], unique=False)
        batch_op.create_index('ix_opportunity_deadline_active', ['deadline', 'is_active'], unique=False)
        batch_op.create_index('ix_opportunity_live', ['is_active', 'is_demo', 'category'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('federal_state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('current_role', sa.String(length=200), nullable=True),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('industries', app.db.base.StringList(), nullable=False),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('education', app.db.base.JsonDict(), nullable=False),
    sa.Column('certifications', app.db.base.JsonDict(), nullable=False),
    sa.Column('languages', app.db.base.JsonDict(), nullable=False),
    sa.Column('desired_additional_monthly_minor', sa.Integer(), nullable=True),
    sa.Column('minimum_worthwhile_minor', sa.Integer(), nullable=True),
    sa.Column('current_primary_income_type', sa.String(length=80), nullable=True),
    sa.Column('income_preference', sa.String(length=32), nullable=False),
    sa.Column('hours_per_week', sa.Float(), nullable=True),
    sa.Column('schedule_preference', sa.String(length=32), nullable=False),
    sa.Column('remote_preference', sa.String(length=16), nullable=False),
    sa.Column('willing_to_travel', sa.String(length=16), nullable=False),
    sa.Column('work_status', sa.String(length=40), nullable=False),
    sa.Column('has_gewerbe', sa.String(length=16), nullable=False),
    sa.Column('has_freelance_tax_registration', sa.String(length=16), nullable=False),
    sa.Column('knows_employer_rules', sa.String(length=16), nullable=False),
    sa.Column('receives_employment_benefits', sa.String(length=24), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_history', app.db.base.JsonDict(), nullable=False),
    sa.Column('checklist', app.db.base.JsonDict(), nullable=False),
    sa.Column('documents_needed', app.db.base.StringList(), nullable=False),
    sa.Column('questions_to_verify', app.db.base.StringList(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('drafts', app.db.base.JsonDict(), nullable=False),
    sa.Column('reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_application_user_opp')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('ix_application_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)

    op.create_table('feedback_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=True),
    sa.Column('question', sa.String(length=64), nullable=False),
    sa.Column('answer', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_events_answer'), ['answer'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_question'), ['question'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_user_id'), ['user_id'], unique=False)

    op.create_table('opportunity_evidence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=False),
    sa.Column('field_name', sa.String(length=60), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=160), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunity_evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_opp_field', ['opportunity_id', 'field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_evidence_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_evidence_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('opportunity_matches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('components', app.db.base.JsonDict(), nullable=False),
    sa.Column('hard_failures', app.db.base.JsonDict(), nullable=False),
    sa.Column('uncertainties', app.db.base.JsonDict(), nullable=False),
    sa.Column('explanation_inputs', app.db.base.StringList(), nullable=False),
    sa.Column('actionability_score', sa.Integer(), nullable=False),
    sa.Column('actionability_band', sa.String(length=24), nullable=False),
    sa.Column('actionability_factors', app.db.base.JsonDict(), nullable=False),
    sa.Column('weights_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_match_user_opportunity')
    )
    with op.batch_alter_table('opportunity_matches', schema=None) as batch_op:
        batch_op.create_index('ix_match_ranking', ['user_id', 'total_score', 'actionability_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_matches_actionability_score'), ['actionability_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_matches_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_matches_total_score'), ['total_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_matches_user_id'), ['user_id'], unique=False)

    op.create_table('profile_skills',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('years', sa.Float(), nullable=True),
    sa.Column('evidence', sa.String(length=20), nullable=False),
    sa.Column('related', app.db.base.StringList(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'key', name='uq_profile_skill')
    )
    with op.batch_alter_table('profile_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_skills_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_skills_profile_id'), ['profile_id'], unique=False)

    op.create_table('saved_opportunities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismiss_reason', sa.String(length=32), nullable=True),
    sa.Column('dismiss_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_saved_user_opp')
    )
    with op.batch_alter_table('saved_opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_opportunities_dismiss_reason'), ['dismiss_reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_opportunities_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_opportunities_user_id'), ['user_id'], unique=False)

    op.create_table('income_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=True),
    sa.Column('income_stream_id', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tax_treatment', sa.String(length=10), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('money_state', sa.String(length=16), nullable=False),
    sa.Column('hours_spent', sa.Float(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("money_state IN ('SECURED','EARNED')", name='ck_income_is_committed'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['income_stream_id'], ['income_streams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_events_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_events_money_state'), ['money_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_events_occurred_on'), ['occurred_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_income_user_date', ['user_id', 'occurred_on'], unique=False)


    # An ANN index over the knowledge corpus. Created only when the extension is
    # actually present; lists=100 suits a corpus in the low thousands of chunks,
    # which is the size this corpus is designed to stay.
    if bind.dialect.name == "postgresql":
        has_vector = bind.exec_driver_sql(
            "SELECT 1 FROM pg_extension WHERE extname = 'vector'"
        ).scalar()
        if has_vector:
            op.execute(
                "CREATE INDEX IF NOT EXISTS ix_knowledge_chunks_embedding "
                "ON knowledge_chunks USING ivfflat (embedding vector_cosine_ops) "
                "WITH (lists = 100)"
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_events', schema=None) as batch_op:
        batch_op.drop_index('ix_income_user_date')
        batch_op.drop_index(batch_op.f('ix_income_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_income_events_occurred_on'))
        batch_op.drop_index(batch_op.f('ix_income_events_money_state'))
        batch_op.drop_index(batch_op.f('ix_income_events_application_id'))

    op.drop_table('income_events')
    with op.batch_alter_table('saved_opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_opportunities_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_opportunities_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_saved_opportunities_dismiss_reason'))

    op.drop_table('saved_opportunities')
    with op.batch_alter_table('profile_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_skills_profile_id'))
        batch_op.drop_index(batch_op.f('ix_profile_skills_key'))

    op.drop_table('profile_skills')
    with op.batch_alter_table('opportunity_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_matches_user_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_matches_total_score'))
        batch_op.drop_index(batch_op.f('ix_opportunity_matches_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_matches_actionability_score'))
        batch_op.drop_index('ix_match_ranking')

    op.drop_table('opportunity_matches')
    with op.batch_alter_table('opportunity_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_evidence_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_evidence_field_name'))
        batch_op.drop_index('ix_evidence_opp_field')

    op.drop_table('opportunity_evidence')
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_reason'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_question'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_answer'))

    op.drop_table('feedback_events')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_opportunity_id'))
        batch_op.drop_index('ix_application_user_status')

    op.drop_table('applications')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_expires_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_user_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index('ix_opportunity_live')
        batch_op.drop_index('ix_opportunity_deadline_active')
        batch_op.drop_index(batch_op.f('ix_opportunities_source_type'))
        batch_op.drop_index(batch_op.f('ix_opportunities_source_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_safety_verdict'))
        batch_op.drop_index(batch_op.f('ix_opportunities_remote_type'))
        batch_op.drop_index(batch_op.f('ix_opportunities_organization'))
        batch_op.drop_index(batch_op.f('ix_opportunities_is_demo'))
        batch_op.drop_index(batch_op.f('ix_opportunities_is_active'))
        batch_op.drop_index(batch_op.f('ix_opportunities_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_opportunities_deadline'))
        batch_op.drop_index(batch_op.f('ix_opportunities_country'))
        batch_op.drop_index(batch_op.f('ix_opportunities_category'))

    op.drop_table('opportunities')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_kind'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index('ix_notification_unread')

    op.drop_table('notifications')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_success'))
        batch_op.drop_index('ix_llm_usage_purpose_time')
        batch_op.drop_index(batch_op.f('ix_llm_usage_purpose'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_provider'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_model'))

    op.drop_table('llm_usage')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_topic'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_document_id'))
        batch_op.drop_index('ix_chunk_topic_year')

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('income_streams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_streams_user_id'))
        batch_op.drop_index(batch_op.f('ix_income_streams_status'))
        batch_op.drop_index(batch_op.f('ix_income_streams_money_state'))
        batch_op.drop_index(batch_op.f('ix_income_streams_category'))

    op.drop_table('income_streams')
    with op.batch_alter_table('income_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_goals_user_id'))
        batch_op.drop_index(batch_op.f('ix_income_goals_is_active'))

    op.drop_table('income_goals')
    with op.batch_alter_table('financial_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_goals_user_id'))
        batch_op.drop_index(batch_op.f('ix_financial_goals_goal_type'))

    op.drop_table('financial_goals')
    with op.batch_alter_table('cv_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cv_documents_user_id'))

    op.drop_table('cv_documents')
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_index('ix_consent_user_purpose')
        batch_op.drop_index(batch_op.f('ix_consent_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_consent_records_purpose'))

    op.drop_table('consent_records')
    with op.batch_alter_table('child_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_child_goals_user_id'))

    op.drop_table('child_goals')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index('ix_analytics_name_time')
        batch_op.drop_index(batch_op.f('ix_analytics_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_name'))

    op.drop_table('analytics_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_demo'))
        batch_op.drop_index(batch_op.f('ix_users_external_auth_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('opportunity_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_sources_source_type'))
        batch_op.drop_index(batch_op.f('ix_opportunity_sources_is_enabled'))

    op.drop_table('opportunity_sources')
    with op.batch_alter_table('legal_facts', schema=None) as batch_op:
        batch_op.drop_index('ix_legal_lookup')
        batch_op.drop_index(batch_op.f('ix_legal_facts_verification_status'))
        batch_op.drop_index(batch_op.f('ix_legal_facts_last_verified_at'))
        batch_op.drop_index(batch_op.f('ix_legal_facts_jurisdiction'))
        batch_op.drop_index(batch_op.f('ix_legal_facts_effective_from'))
        batch_op.drop_index(batch_op.f('ix_legal_facts_category'))

    op.drop_table('legal_facts')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_topic'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_effective_year'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_content_available'))

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_subject_hash'))
        batch_op.drop_index(batch_op.f('ix_audit_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
