"""store the user's stated monthly target

Revision ID: dd3d96315849
Revises: 262afc3549c4
Create Date: 2026-09-09 09:50:03.922150
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# The custom column types (UtcDateTime, JsonDict, StringList, Vector) are
# rendered by autogenerate as `app.db.base.X` but the import is not emitted
# with them, so every migration that touches one fails at import time.
# Importing it unconditionally costs nothing and removes the trap.
import app.db.base  # noqa: F401


revision: str = 'dd3d96315849'
down_revision: str | None = '262afc3549c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_monthly_minor', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('target_monthly_minor')

    # ### end Alembic commands ###
